plugins { id 'com.android.application' }

android {
    namespace 'jp.haruya.asnposterinput'
    compileSdk 35

    defaultConfig {
        applicationId 'jp.haruya.asnposterinput'
        minSdk 26
        targetSdk 34
        versionCode 6
        versionName '1.5'
    }
    sourceSets { main { assets.srcDirs += file('../../www') } }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies { implementation 'androidx.webkit:webkit:1.12.1' }
